ejournal/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^journal/', include('journal.urls')),
]

journal/urls.py
from django.conf.urls import url

from . import views

app_name = 'journal'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^detail/$', views.detail, name='detail')
]

journal/models.py
from django.db import models

    
class Class(models.Model):
    name      = models.CharField(max_length = 5)

    def __str__(self):
        return self.name

class Student(models.Model):
    name         = models.CharField(max_length = 30)
    surname      = models.CharField(max_length = 30)
    password     = models.CharField(max_length = 20)
    classes      = models.ForeignKey(Class, on_delete = models.CASCADE)
    
    def __str__ (self):
        return self.name + " " + self.surname

class Subject(models.Model):
    name = models.CharField(max_length = 30)

    def __str__ (self):
        return self.name

        
class Mark(models.Model):
    student   = models.ForeignKey(Student, on_delete = models.CASCADE)
    subject   = models.ForeignKey(Subject, on_delete = models.CASCADE)
    mark      = models.IntegerField(default = 0)
    date      = models.DateTimeField('date')
    explain   = models.CharField(max_length = 50)

    def __str__ (self):
        return "{0} получил {1} по предмету {2}".format(self.student, self.mark, self.subject)

    

journal/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.template import loader

from .models import Student, Mark, Subject, Class

def index(request):
    students = Student.objects.all()
    subjects = Subject.objects.all()
    classes  = Class.objects.all()
    template = loader.get_template('journal/index.html')
    context = {
        'students' : students,
        'subjects' : subjects,
        'classes'  : classes,
    }
    return HttpResponse(template.render(context, request))

def wrong_pass(request):
    template = loader.get_template('journal/wrong_pass.html')
    return HttpResponse(template.render({}, request))
    
def detail_all(request):
    _student_id = request.POST['student']
    _password   = request.POST['password']

    marks = Mark.objects.filter(student_id = _student_id);
    student = marks[0].student
    subjects= Subject.objects.all()
    marks = reversed(marks)
    
    if _password != student.password:
        return wrong_pass(request)
    
    template = loader.get_template('journal/detail_all.html')
    context  = {
        "student": student,
        "subjects": subjects,
        "marks": marks,
    }
    
    return HttpResponse(template.render(context, request))

def detail(request):
    _subject_id = request.POST['subject']
    if _subject_id == "-1":
        return detail_all(request)

    _student_id = request.POST['student']
    _password   = request.POST['password']
    #_class_id   = request.POST['class']

    marks = Mark.objects.filter(student_id = _student_id, subject_id = _subject_id);
    student = marks[0].student
    subjcet = marks[0].subject    
    marks = reversed(marks)
    
    if _password != student.password:
        return wrong_pass(request)
    
    template = loader.get_template('journal/detail.html')
    context = {
        "marks": marks,
        "student": student,
        "subject": subjcet,
    }
    return HttpResponse(template.render(context, request))

journal/templates/journal/detail.html
<head>
  
  <title>
    Electronic Journal
  </title>
  {% load static %}

  <link rel="stylesheet" type="text/css" href="{% static 'journal/style.css' %}">
</head>
<body>
  <div id="Main">
    <h1>{{student}}</h1>
    <h2>{{subject}}</h2>

    <table>
      <tr>
	<th>Оценка</th>
	<th>Дата</th>
	<th>Описание</th>
      </tr>
      {% for m in marks %}
      <tr>
	<td>{{ m.mark }}</td>
	<td>{{ m.date.day }}.{{m.date.month}}.{{m.date.year}}</td>
	<td>{{ m.explain }}</td>
      </tr>
      {% endfor%}
    </table>
  </div>
  <div id="author">
    Developed by Misiura Rostislav
  </div>
<body>

journal/templates/journal/detail_all.html
<head>
  
  <title>
    Electronic Journal
  </title>
  {% load static %}

  <link rel="stylesheet" type="text/css" href="{% static 'journal/style.css' %}">
</head>
<body>
  <div id="Main">
    <h1>{{student}}</h1>
    <h2>{{subject}}</h2>

    <table>
      <tr>
	<th>Предмет</th>
      </tr>
      {% for subject in subjects %}
      <tr>
	<td>{{ subject }}</td>
	{% for mark in marks %}
	{% if mark.subject == subject %}
	<td>{{ mark.mark }}</td>
	{% endif %}
	{% endfor %}
      </tr>
      {% endfor%}
    </table>
  </div>
  <div id="author">
    Developed by Misiura Rostislav
  </div>
<body>

journal/templates/journal/index.html
<head>
  <title>
    Electronic Journal
  </title>
  {% load static %}

  <link rel="stylesheet" type="text/css" href="{% static 'journal/style.css' %}">
</head>
<body>
  <div id="Main">
    <h1>Electronic Journal</h1>

    <form action="{% url 'journal:detail' %}" method="post">
      {% csrf_token %}
      <div id="form">
	<p>
	  <!--
	  Класс:
	  <select name = "class" onchange = "">
	    {% for c in classes %}
	    <option value={{c.id}}>{{c}}</option>
	    {% endfor %}
	  </select>
	  -->
	  Ученик:
	  <select name = "student">
	    {% for s in students %}
	    <option value={{s.id}}>{{s}}</option>
	    {% endfor %}
	  </select>
	</p>
	
	<p>Предмет:
	  <select name = "subject">
	    <option value=-1>Показать все предметы</option>
	    {% for s in subjects %}
	    <option value={{s.id}}>{{s}}</option>
	    {% endfor %}
	  </select>
	</p>

	<p>Пароль:
	  <input type="password" name="password"></input>
	</p>
      </div>
      <input id="submit" type="Submit" value="Подтвердить" >
    </form>
  </div>
  <div id="author">
    Developed by <a href="#">Misiura Rostislav</a>
  </div>
</body>

journal/templates/journal/wrong_pass.html
<head>
  <title>
    Electronic Journal
  </title>
  {% load static %}

  <link rel="stylesheet" type="text/css" href="{% static 'journal/style.css' %}">
</head>
<body>
  <div id="Main">
    <h1>Неправильный пароль</h1>
  </div>
  <div id="author">
    Developed by Misiura Rostislav
  </div>
</body>